### ISSUE TITLE
Examples - R vs Python

### ISSUE THREAD

**Issue by stared** [TyberiusPrime/pyggplot#3]
As some wrapping is non-trivial, a list of examples (and ideally, with their analogous R code) would be beneficial. Especially as it is typically easier to learn from direct, working examples than descriptions (even if very long and accurate).

Some things require changes, e.g. instead of R

```
scale_color_brewer(type='diverging', palette=2)
```

one need to write

```
scale_color_brewer('diverging', palette=2)
```

as `type` is a Python keyword.

BTW: How to use `add_smooth`? I have tried but without success.

BTW: Why `add_` not just `geom_`?

**Comment by TyberiusPrime** [comment]
Hello Piotr,

you're right we need to add some examples - I'll go and find some - after all, I've been using the library internally for a few years now. Though most of that time it was with pydataframes.

I'll look into add_smooth - can't do tests from this machine right now.

What you do in R is you _add_ geoms to existing plot objects, and
I wanted to keep that semantic. But the 'geom' part only makes sense in a language like R,
lacking namespaces and having a function based dispatching mechanism (as opposed
to python methods which are always bound to an object). I'd have found it tedious
to type add_geom in front of everything.

It'd be trivial to change the code to have two functions add_\* and geom_\* though, 
since they're all dynamically generated anyhow (even without monkeying with **getattr**).

**Comment by stared** [comment]
In the first place, thanks for sharing! 

If really needed, it is possible to do the yhat-ggplot way with namespace like `import ggplot as gg`, so to avoid nasty `*` imports. But for me chaining with dot is as good as adding. So, at least to my eyes, the Pythonic equivalent of `+` in R would be `.` chaining. And I would drop `add_` word (to keep as naming as close as possible to R - it is easier to have code looking as similar as possible).

For showing how it works, IMHO the best way to provide a relevant IPython Notebook.

Plus, a list of all ggplot function with indication if they work or not would be very beneficial (saving a lot of guessing game).

Or some naming things. For example `geom_abline` is here `add_ab_line` (not sure if intended).

**Comment by TyberiusPrime** [comment]
ok, I made some progress on the examples http://tyberiusprime.github.io/pyggplot/pyggplot%20samples.html
and we now have a nice github page http://tyberiusprime.github.io/pyggplot/

Yes, the names have generally been pythonized to conform more closely to PEP8  ("Function names should be lowercase, with words separated by underscores as necessary to improve readability.").

I'm not a huge fan of having the same functionality available under different names, but I guess I could be convinced to also load the geoms under geom_*, and without underscores...

yhat-ggplot approach is the most unpythonic way to go about this and I really don't want to go there.

Please note that our add_\* do not return individual objects - instead they modify the plot object and return that - so '.' chaining is already possible.

**Comment by stared** [comment]
Great!

`ggplot2` to a large extent uses underscore convention. And I don't think that we should be overzealous about Pythonic convention (from Zen of Python: "practicality beats purity"); especially as most of Python things are not putting `_` everywhere (think about `randomint`); the only bad thing here is `camelCase`. So I really wouldn't redefine ggplot2 names just to add one more `_`.

Also, I really encourage using standard `gg` as the standard shortcut (alike `numpy` -> `np`, `pandas` -> `pd`). I think that writting

```
import pyggplot as gg

# loading data

p = gg.Plot(df)
```

is downright marvelous (and Pythonic).

I know that it returns objects and allows chaining -> its why I like it.

BTW: Can I do `aes` in some way? What is exactly `add_scatter` as I see no thing with the same name in `ggplot2` docs?

**Comment by TyberiusPrime** [comment]
I like the gg part :) - and I´ll change the examples accordingly.

I´m also open to adding aliases - ggplot does it with color vs colour - so we can do the pythonic (_) and R names. 

Aes() I consider a wart - ggplot should really have gone the other way around, have parameters by default be aes, and use something like I() to specify values.
We by default turn everything that is a column in our DataFrame into an aes parameter - everything else get´s passed as a regular parameter.

add_scatter is an alias for add_point - guess we should replace it with add_point in the examples.

**Comment by stared** [comment]
Yeah, I don't miss `aes`. Though, shouldn't it work like `ggplot`?

I.e. in R I can write

```
ggplot(df, aes(x, y)) + geom_point()
```

isn't there a way to do it same in this wrapper,

   gg.Plot(df, 'x', 'y').geom_point()

(I mean, an equivalent of just removing `aes`). 

When it comes to naming, the point is not learning again new functions (even if their change is trial, but nonetheless had to be guessed). For sure you know and are comfortable with the current naming, but if you want this library to catch up, I strongly suggest keeping original names whenever possible or making changes only when it is necessary. So, keeping old names makes sense both for old users of ggplot, and new ones, who can directly Google function and get reference from ggplot.

For example, except for `geom_point` -> `set_scatter` (which defeats the purpose, as the first impression of anyone trying to find a ggplot wrapper will be that it is a different function). Similarly, for `ggtitle`, `gg` is obviously for namespace, so I would suggest just title `title` (an easy rule: whenever it start with `gg`, then it is being dropped).

**Comment by TyberiusPrime** [comment]
Right now, the aes must be set on the geoms - though later geoms can steal their required aes from previous ones - they don't steal their optional aes though.

I guess we could add them as keyword parameters on the plot object, but I'm not a big fan of the 'say it however you like it' approach ggplot2 is taking here.
And since you can map different columns onto the same axis (especially when you pass in other dataframes with data= on the geoms), it suggests to me that the mapping is a feature of the geom, not the plot itself.

I'll add the geom_\* as aliases for the add_\* functions though and update the examples accordingly.

**Comment by TyberiusPrime** [comment]
Ok, we now support geom_\* and the examples have been corrected accordingly.
Any discrepancy from the expected syntax should go into a new issue, I'm closing this one.
